### ISSUE TITLE
anchor fantasies

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#10]
search for 
```
href="fantasy-
```

replace that with
```
href="#fantasy-
```

search for
```
id="#fantasy-species-gnome"
```

replace with 

```
id="fantasy-species-gnome"
```

There could be others I was looking for gnome and the links didn't work and spot checked a couple others.

**Comment by callmepartario** [comment]
nice one. should be fixed in https://github.com/callmepartario/og-csrd/commit/d42c63dbe985866873d81a2dcf363418879c1da7 - i'll try to get a full regex run this week and catch anything that lingers.
