### ISSUE TITLE
Ikwiikwii descriptor, stat Pool prefix

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#11]
https://callmepartario.github.io/og-csrd/og-dd.html#descriptor-ikwiikwii

Descriptor might/should be named something not descriptor?

You gain the following characteristics:
Descriptor: +2 to your Might Pool and +2 to your Intellect Pool.
Skill: You're trained in perception and tracking.
....

**Comment by callmepartario** [comment]
`Descriptor:` should read `Savage Cunning:`

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)
