### ISSUE TITLE
Can Devour Anything focus, Tier 2 ability formatting

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#12]
https://callmepartario.github.io/og-csrd/og-dd.html#focus-can-devour-anything

Formatting wise, I think the two abilities listed in Tier 2 should be separate lines to match all the other lists?
I'm assuming that's not an OR situation.

Tier 1: [Bad Attitude](https://callmepartario.github.io/og-csrd/og-dd.html#ability-bad-attitude)
Tier 1: [True Omnivore](https://callmepartario.github.io/og-csrd/og-dd.html#ability-true-omnivore)
Tier 2: [Eat Anything](https://callmepartario.github.io/og-csrd/og-dd.html#ability-eat-anything), [Redundant Organs](https://callmepartario.github.io/og-csrd/og-dd.html#ability-redundant-organs)
Tier 3: [Eidetic Epicurean](https://callmepartario.github.io/og-csrd/og-dd.html#ability-eidetic-epicurean) or [Capable Warrior](https://callmepartario.github.io/og-csrd/index.html#ability-greater-enhanced-might) (118)
Tier 4: [Breaker](https://callmepartario.github.io/og-csrd/index.html#ability-breaker) (116)
Tier 4: [Maw](https://callmepartario.github.io/og-csrd/og-dd.html#ability-maw)
Tier 5: [Greater Enhanced Might](https://callmepartario.github.io/og-csrd/index.html#ability-greater-enhanced-might) (146)
Tier 6: [Lethal Damage](https://callmepartario.github.io/og-csrd/index.html#ability-lethal-damage) (158) or [Regenerate](https://callmepartario.github.io/og-csrd/index.html#ability-regenerate) (175)
...
Like this:
Tier 1: [True Omnivore](https://callmepartario.github.io/og-csrd/og-dd.html#ability-true-omnivore)
Tier 2: [Eat Anything](https://callmepartario.github.io/og-csrd/og-dd.html#ability-eat-anything)
Tier 2: [Redundant Organs](https://callmepartario.github.io/og-csrd/og-dd.html#ability-redundant-organs)
Tier 3: [Eidetic Epicurean](https://callmepartario.github.io/og-csrd/og-dd.html#ability-eidetic-epicurean) or [Capable Warrior](https://callmepartario.github.io/og-csrd/index.html#ability-greater-enhanced-might) (118)

**Comment by callmepartario** [comment]
good shout, i will address this

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)
