### ISSUE TITLE
Ghostly Terror ability description, delete extra "Action."

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#13]
duplicated words:

https://callmepartario.github.io/og-csrd/og-dd.html#ability-ghostly-terror

Ghostly Terror (6 Intellect points): You create a horrific and twisted visage of yourself, growing to twice your usual size. For the next minute, you gain an asset on intimidation tasks. Creatures within short range may become frightened; make a separate Intellect attack roll for each creature. You decide if the target is frozen in fear or compelled to flee. Either way, they cannot take actions other than to move away from you unless you allow it. The effects on a target end if they are attacked. **Action. Action.**

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)
