### ISSUE TITLE
Improved Hold-All ability description, delete extra "Enabler."

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#14]
https://callmepartario.github.io/og-csrd/og-dd.html#ability-improved-hold-all

Just my two cents. Only mention Enabler at the end or remove it from the end as it's included in the two options?

Improved Hold-All: Your [Handy Hold-All](https://callmepartario.github.io/og-csrd/og-dd.html#ability-handy-hold-all)'s level increases by 1. Additionally, choose one of the following modifications:
Cypher Pod. The handy hold-all can carry and activate one extra manifest cypher for you. Enabler.
Climb. The handy hold-all can climb natural steep and near-vertical surfaces, including carrying you with it. Enabler.
Enabler.

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)
