### ISSUE TITLE
Flash Petrification ability description, "Amor" should be "Armor"

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#15]
Typo in Armor (unless there's some relationship type impact I'm not thinking of here :smile:  )

Flash Petrification (1+ Intellect or Speed points): You can use your curse to petrify parts of yourself at strategic moments. When your Might Pool would be damaged, you can pay this ability's cost from your Speed or Intellect Pool. The cost is equal to the damage inflicted (after accounting for **Amor**). Enabler.

**Comment by callmepartario** [comment]
haha, clearly i have seen one too many episodes of *Gargoyles*. `Amor` should indeed read `Armor`.

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)
