### ISSUE TITLE
On Leather Wings ability description missing "points"

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#16]
to match the other entries

On Leather Wings (4 Might): You unfurl your wings, and for the next ten minutes, you can fly a short distance each round and still take another action. Carrying another creature with you counts as this additional action. Enabler.

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f
