### ISSUE TITLE
In some cyphers, "Effects:" should be "Effect:" (see list)

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#20]
In cyphers:
Convenient Barricade
Inescapable Sight
Lie Detector
Strike First

should be singular 'Effect:'

<strong>Effect:</strong>

	<h5 class="og-csrd-header-h5-icon" id="cypher-convenient-barricade">Convenient Barricade<span data-toggle="tooltip" title="Subtle Cypher" class="og-csrd-icon og-csrd-cypher-subtle ms-1"></span><span data-toggle="tooltip" title="Fantastic Cypher" class="og-csrd-icon og-csrd-cypher-fantastic ms-1"></span><a class="og-csrd-header-anchor" href="#cypher-convenient-barricade" title="Permalink" aria-hidden="true"></a></h5>
	<ul class="list-unstyled og-csrd-indent-hang">
		<li><p><strong>Level:</strong> 1d6 + 4</p></li>
		<li><p><strong>Effects:</strong> You create or find a barrier&mdash;for example, a thick closed door, a force field, a convenient wall collapse, or even something intangible, like a psychological block&mdash;between you and a source of danger. For a number of rounds equal to the cypher level, nothing can bypass the barrier in either direction. You cannot end this effect early.</p></li>

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)

**Comment by davebytemfg** [comment]
this appears to not be corrected on main

**Comment by callmepartario** [comment]
got it, here's the updated list to check for foundry:
- Convenient Barricade
- Convenient Mistake
- Inescapable Sight
- Lie Detector
- Strike First
