### ISSUE TITLE
Sudden Tribute, "d20" should be "d100", missing 98 value in roll table

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#21]
0) instructions suggest rolling a d20
1) it's a bit odd this the table is d100 and all the other cyphers are d6 / d10 
2) We enter a causality wormhole if we roll a 98 

SUDDEN TRIBUTE
Level: 1d6

Effect: A friendly NPC grants you something within their their means to give. The GM chooses the specific item. Roll a d20 to determine nature of the gift:

Sudden Tribute Effects
d100	Tribute Item
01–40	Expensive item
41–65	Very expensive item
66–85	Cypher
86–92	Exorbitant item
93–97	Artifact
99–00	Priceless item

**Comment by callmepartario** [comment]
fixed in https://github.com/callmepartario/og-csrd/commit/6529ce772b85d795757cca4793afc59390497c6f

leaving this issue open until it's fixed in the [Cypher Community Content Module](https://github.com/mrkwnzl/cyphersystem-community-module)
