### ISSUE TITLE
Adjustments to French Character Sheet CSCS

### ISSUE THREAD

**Issue by edralzar** [callmepartario/og-csrd#26]
Hey there ! First off, many thanks for the OG-CSRD and all the tools and tidbits you put out there 👍 

I'm French and I was happy to use the CSCS, but I noticed a few mistakes:

 - the desc/type/focus section: in French, adjectives go after the name so the order should be TYPE/DESCRIPTOR/FOCUS
 - better translations for these three elements would be `Type`/`Descripteur`/`Focus` (that's how the first edition of Numenera is translated in French). Similarly, I'd say `Variante` would be a better translation for Flavor
 - typo: ET UN/UNE -> `EST UN/UNE`
 - damage track section; typo CURSUER -> `CURSEUR`, PLEIN FORME -> `PLEINE FORME`
 - recovery section: typo 10 HUERES -> `10 HEURES`

Hope this helps 👍

**Comment by callmepartario** [comment]
thanks so much, i will make these changes and get a new version uploaded soon.

**Comment by callmepartario** [comment]
a new version has been uploaded with these changes. merci!
