### ISSUE TITLE
Broken internal links

### ISSUE THREAD

**Issue by larvanitis** [callmepartario/og-csrd#30]
In [index.html](https://github.com/callmepartario/og-csrd/blob/main/index.html), the following link destinations do not exist.

- builds-robots
- choose-traps
- currency-and-prices
- equipment
- focus-Leads
- modifying-abilities-using-initial-costs
- player-intrusions

Obtained using
```js
[...new Set([...document.querySelectorAll(`a[href^="#"]`)].map(el => el.getAttribute('href').trim().slice(1)))].sort().filter(id => id && !document.getElementById(id))
```

---

Also, the anchor _Editorial Additions > **Old Gus' Daft Drafts (OG-DD)**_ should probably link to `og-dd.html`.

**Comment by callmepartario** [comment]
Thanks for these finds, I had been meaning to run a full check on this and kept getting distracted with other things.

Should all be fixed in https://github.com/callmepartario/og-csrd/commit/9281b2d47ad8556450dcd07b62976eee93f155b4
