### ISSUE TITLE
WAAAMH typo

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#6]
There's a couple of references to WAAAMH that should be WAAMH instead.

Figured it would be easier for you to search/replace.

one example is 

```
			<li><a href="#suggested-types-for-a-fairy-tale-game">Types</a> <span class="og-csrd-ref">(WAAAMH, 64)</span></li>
```

**Comment by callmepartario** [comment]
thanks; these have been resolved.
