### ISSUE TITLE
Inconsistent page numbers

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#7]
I have not yet had the time to review all of these, spot checking seems to indicate at some of them are pdf vs printed page confusions, while others might just be typos or from different editions then I have access to.  But I was able to automate the detection of them and get a reasonable list, so I thought I'd share.

I may have time next week to dig into these more completely but wanted to highlight them for you in the mean time.

Thanks for the excellent resource and all the work to pull this together, really useful.

```
conflicting page numbers for :Assassin Skills :111 or 110 #ability-assassin-skills
conflicting page numbers for :Assassin Skills :110 or 111 #ability-assassin-skills
conflicting page numbers for :Dimensional Modulator :90 or 89 #science-fiction-artifact-dimensional-modulator
conflicting page numbers for :Dimensional Modulator :89 or 90 #science-fiction-artifact-dimensional-modulator
conflicting page numbers for :Discerning Mind :130 or 129 #ability-discerning-mind
conflicting page numbers for :Discerning Mind :129 or 130 #ability-discerning-mind
conflicting page numbers for :Drain at a Distance :191 or 131 #ability-drain-at-a-distance
conflicting page numbers for :Drain at a Distance :131 or 191 #ability-drain-at-a-distance
conflicting page numbers for :Driving on the Edge :132 or 118 #ability-driving-on-the-edge
conflicting page numbers for :Driving on the Edge :118 or 132 #ability-driving-on-the-edge
conflicting page numbers for :Duel to the Death :147 or 132 #ability-duel-to-the-death
conflicting page numbers for :Duel to the Death :132 or 147 #ability-duel-to-the-death
conflicting page numbers for :Grand Deception :146 or 127 #ability-grand-deception
conflicting page numbers for :Grand Deception :127 or 146 #ability-grand-deception
conflicting page numbers for :Hard Target :148 or 139 #ability-hard-target
conflicting page numbers for :Hard Target :139 or 148 #ability-hard-target
conflicting page numbers for :Hard to Kill :149 or 148 #ability-hard-to-kill
conflicting page numbers for :Hard to Kill :148 or 149 #ability-hard-to-kill
conflicting page numbers for :Insight :164 or 154 #ability-insight
conflicting page numbers for :Insight :154 or 164 #ability-insight
conflicting page numbers for :Make Judgment :160 or 159 #ability-make-judgement
conflicting page numbers for :Make Judgment :159 or 160 #ability-make-judgement
conflicting page numbers for :Mind Control :162 or 152 #ability-mind-control
conflicting page numbers for :Mind Control :152 or 162 #ability-mind-control
conflicting page numbers for :Mind Games :162 or 152 #ability-mind-games
conflicting page numbers for :Mind Games :152 or 162 #ability-mind-games
conflicting page numbers for :Natural Crafter :174 or 165 #ability-natural-crafter
conflicting page numbers for :Natural Crafter :165 or 174 #ability-natural-crafter
conflicting page numbers for :Out of Harm's Way :187 or 167 #ability-out-of-harms-way
conflicting page numbers for :Out of Harm's Way :167 or 187 #ability-out-of-harms-way
conflicting page numbers for :Phase Detonation :169 or 168 #ability-phase-detonation
conflicting page numbers for :Phase Detonation :168 or 169 #ability-phase-detonation
conflicting page numbers for :Poison Crafter :170 or 156 #ability-poison-crafter
conflicting page numbers for :Poison Crafter :156 or 170 #ability-poison-crafter
conflicting page numbers for :Quarry :183 or 173 #ability-quarry
conflicting page numbers for :Quarry :173 or 183 #ability-quarry
conflicting page numbers for :Rapid Processing :176 or 174 #ability-rapid-processing
conflicting page numbers for :Rapid Processing :174 or 176 #ability-rapid-processing
conflicting page numbers for :Resilient Ice Armor :178 or 176 #ability-resilient-ice-armor
conflicting page numbers for :Resilient Ice Armor :176 or 178 #ability-resilient-ice-armor
conflicting page numbers for :Resist the Elements :186 or 176 #ability-resist-the-elements
conflicting page numbers for :Resist the Elements :176 or 186 #ability-resist-the-elements
conflicting page numbers for :Silent As Space :183 or 182 #ability-silent-as-space
conflicting page numbers for :Silent As Space :182 or 183 #ability-silent-as-space
conflicting page numbers for :Tower of Intellect :193 or 192 #ability-tower-of-intellect
conflicting page numbers for :Tower of Intellect :192 or 193 #ability-tower-of-intellect
conflicting page numbers for :Very Long Sprinting :196 or 183 #ability-very-long-sprinting
conflicting page numbers for :Very Long Sprinting :183 or 196 #ability-very-long-sprinting
```

**Comment by callmepartario** [comment]
nice one, this is so helpful. i have fixed this set in https://github.com/callmepartario/og-csrd/commit/4dcd5552d6b5c337c765b0dca1922b67589b6a9d - but please feel free to run this anytime to catch anything i may have missed, this is super helpful.

**Comment by davebytemfg** [comment]
I reran things and it looks all clean with respect to duplicates. Nice!

Upon further review I made these adjustments to my data, not sure exactly what your intent for 'Errata' page numbers were though, so don't know if I'm suggesting for you to make similar changes on your side. I see the case for noting the older versions of Master Entertainer have been cleared up, but there are valid page numbers for these two that I used instead.

Thanks for the quick turnaround!

```
# this is marked as Errata in og-index actually appears on page 67
"ENTERTAINS",67,#focus-og

# this is marked as Errata in og-index actually appears on page 160
"Master Entertainer",160,#ability-og
```

Have you chatted with the publishers on the missing Flex Weapon Skill? That does seem like an Errata entry, but my code wants real page numbers so I'm just fudging things for now.
```
# this ability only exists in the CSRD but likely should be in the core book on page 141?
"Flex Weapon Skill",141,#ability-manual
```

Lastly, just to mix up the comms channels, you made some comment in discord about talking with MonteCook about some CSRD page number question, but I couldn't actually find your detailed comment in #cypher_creators, anything specific you can share would be appreciated!

**Comment by callmepartario** [comment]
The entertains got a rework in the latest CSRD, which subs in Inspiring Ease for Inspiration at Tier 2. As a result, the Master Entertainer ability now refers to the new Tier 2 ability. I marked it as errata to call attention to the fact that the text in the CSRD is different than what's in the Cypher System Rulebook. (there are editor's notes on the affected abilities explaining this).

Flex Weapon Skill is an orphan (not appearing in a focus) ability in Claim the Sky, I'll get that change implemented; i thought I had caught all those. I didn't own that book until recently, so I had thought they were additional Errata, but they're not.

It took a while but i got my response just this week from MCG. I do need to go back and share it in the CU channel, i will go ahead and do that right now!

**Comment by davebytemfg** [comment]
perfect, makes sense and thanks for the message in CU.
