### ISSUE TITLE
Handling of &dagger;

### ISSUE THREAD

**Issue by davebytemfg** [callmepartario/og-csrd#8]
This is super tiny, and might just be my opinion, but throwing it out anyway

```
				<li><a href="#ability-regenerate">Regenerate&dagger;</a> <span class="og-csrd-ref">(175)</span></li>
```

should more likely be

```
				<li><a href="#ability-regenerate">Regenerate</a><span class="og-csrd-ref">(175)</span>&dagger;</li>
```

That was the only case where &dagger; appeared inside the anchor tags, other uses have it outside.

**Comment by callmepartario** [comment]
nice one, fixed in https://github.com/callmepartario/og-csrd/commit/4dcd5552d6b5c337c765b0dca1922b67589b6a9d
